import { ProfileData } from '@/types/profile';

export const mockProfiles: ProfileData[] = [
  {
    _id: 'profile-dev-1',
    status: 'professional',
    type: 'individual',
    groupId: 'group-1',
    theme: {
      color: 'blue',
    },
    firstName: 'Mohammed',
    fullName: 'Mohammed Developer',
    lastName: 'Developer',
    birthDate: '1990-01-15',
    gender: 'male',
    phoneNumber: '+1234567890',
    companyName: 'Spinet NFC',
    activitySector: 'Technology',
    position: 'Frontend Developer',
    profilePicture: '',
    profileCover: '',
    links: [
      {
        title: 'LinkedIn',
        link: 'https://linkedin.com/in/mohammeddev',
        name: 'LinkedIn',
      },
      {
        title: 'GitHub',
        link: 'https://github.com/mohammeddev',
        name: 'GitHub',
      },
    ],
    lockedFeatures: {
      profileCover: false,
      logo: false,
      qrCodeLogo: false,
      displayLogo: false,
      companyName: false,
      activitySector: false,
      position: false,
      school: false,
      profession: false,
      theme: false,
      canAddLinks: true,
      canAddServices: true,
      excludedLinks: [],
    },
  },
  {
    _id: 'profile-dev-2',
    status: 'company',
    type: 'business',
    groupId: 'group-2',
    theme: {
      color: 'green',
    },
    fullName: 'Spinet NFC Business',
    birthDate: '2020-01-01',
    gender: 'company',
    phoneNumber: '+1987654321',
    companyName: 'Spinet NFC Technologies',
    activitySector: 'Digital Solutions',
    position: 'CEO',
    profilePicture: '',
    profileCover: '',
    links: [
      {
        title: 'Website',
        link: 'https://spinet.com',
        name: 'Website',
      },
      {
        title: 'Twitter',
        link: 'https://twitter.com/spinetnfc',
        name: 'Twitter',
      },
    ],
    lockedFeatures: {
      profileCover: false,
      logo: false,
      qrCodeLogo: false,
      displayLogo: true,
      companyName: false,
      activitySector: false,
      position: false,
      school: false,
      profession: false,
      theme: false,
      canAddLinks: true,
      canAddServices: true,
      excludedLinks: [],
    },
  },
];

export const mockInsights = {
  totalContacts: 127,
  totalLeads: 23,
  totalServices: 8,
  contactsThisMonth: 15,
  leadsThisMonth: 7,
  servicesThisMonth: 2,
  contactsByType: {
    manual: 45,
    scan: 32,
    exchange: 28,
    spinet: 15,
    phone: 7,
  },
  leadsByStatus: {
    pending: 5,
    prospecting: 8,
    'offer-sent': 4,
    negotiation: 3,
    'administrative-validation': 1,
    done: 2,
    failed: 0,
    canceled: 0,
  },
  recentActivity: [
    {
      type: 'contact',
      action: 'added',
      item: 'John Doe',
      date: '2024-01-16',
    },
    {
      type: 'lead',
      action: 'updated',
      item: 'Enterprise SaaS Deal',
      date: '2024-01-15',
    },
    {
      type: 'service',
      action: 'added',
      item: 'Web Development',
      date: '2024-01-14',
    },
  ],
};
